<?php

use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * 	Hook implementations
 */
function spektrix_import_theme() {
  return array(
      'spektrix_import_calendar' => array(
          'template' => 'spektrix_import_calendar',
          'variables' => []
      )
  );
}

/**
 * Hook_preprocess_node()
 */
function spektrix_import_preprocess_node(&$variables) {
  $node = $variables['node'];
  if ($node->type->entity->id() == 'event') {

    // Set this to false by default
    $multiple = FALSE;
    $variables['multiple_perf'] = FALSE;

    // Look up performances referencing this event
    $query = \Drupal::entityQuery('performances');
    $query->condition('field_event.target_id', $node->id());
    $ids = $query->execute();

    // Set var if multiple perfs
    if (count($ids) >= 2) {
      $multiple = TRUE;
      $variables['multiple_perf'] = TRUE;
    }

    // Spektrix events
    if (!empty($node->get('field_spektrix_event_id')->getValue())) {
      if ($multiple) { // Multiple performances - display modal
        $variables['booking_link'] = array(
            '#type' => 'link',
            '#title' => !empty($node->get('field_booking_label')->getValue()) ? $node->get('field_booking_label')->getString() : t('Book Now'),
            '#url' => Url::fromRoute('spektrix_import.calendar_modal', array('prod_id' => $node->get('field_spektrix_event_id')->getValue()[0]['value'])),
            '#attributes' => array(
                'class' => array('use-ajax', 'a-btn'),
                'data-dialog-type' => 'modal',
                'data-dialog-options' => json_encode(array('height' => '70%', 'width' => '80%')),
            ),
        );
      } else { // Single performance - return booking link
        
        if ($ids) {
          $perf = entity_load('performances', array_pop($ids));
          
          if ($perf) {
            
            $btnClasses = 'a-btn';
            
            if (!empty($perf->field_availability)) {
              $availabilityTerm = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($perf->field_availability->getValue()[0]['target_id']);
              if ($availabilityTerm) {
                $availability = $availabilityTerm->getName();              

                if ($availability == 'Sold Out'){
                  $btnClasses = 'a-btn no-click';
                }
              }
            }

            $variables['booking_link'] = array(
              '#type' => 'link',
              '#title' => !empty($node->get('field_booking_label')->getValue()) ? $node->get('field_booking_label')->getString() : $availability,
              '#url' => Url::fromUri(\Drupal::request()->getSchemeAndHttpHost() . '/book/' . $perf->field_spektrix_perf_id->getValue()[0]['value']),
              '#attributes' => array(
                'class' => array($btnClasses),
              )  
            );

            if (isset($perf->field_do_time) && !empty($perf->field_do_time->getValue())) {        
              $do_time = $perf->field_do_time->getValue()[0]['value'];
            }
          }
        }
      }
    }
    // Manually created events
    else {
      
      if ($multiple) {
        $variables['booking_link'] = array(
            '#type' => 'link',
            '#title' => !empty($node->get('field_booking_label')->getValue()) ? $node->get('field_booking_label')->getString() : t('Book Now'),
            '#url' => Url::fromRoute('spektrix_import.calendar_modal_partner', array('prod_id' => $node->id())),
            '#attributes' => array(
                'class' => array('use-ajax', 'a-btn'),
                'data-dialog-type' => 'modal',
                'data-dialog-options' => json_encode(array('height' => '70%', 'width' => '80%')),
            ),
        );
      }
      else {
        if (!empty($node->field_event_booking->getValue())) {
          $variables['booking_link'] = array(
            '#type' => 'link',
            '#title' => $node->field_booking_label->getString(),
            '#url' => Url::fromUri($node->field_event_booking->getString()),
            '#attributes' => array(
              'class' => array('a-btn'),
            )
          );
        }
        else {
          $variables['booking_link'] = array(
            '#markup' =>   '<a href="#" class="a-btn no-click" target="_self" title="'. $node->field_booking_label->getString() .'">'. $node->field_booking_label->getString() .'</a>' 
          );  
        }
      }
    }   

    // Hide run date on past events
    $variables['pastEvent'] = FALSE;
    $run_date = $variables['node']->field_run_date->getValue()[0]['end_value'];
    $to_date = strtotime($run_date);
    if (strtotime('now') >= $to_date) {
      $variables['pastEvent'] = TRUE;
    }

    // Pass on Timezone-aware time
    $start_date = $variables['node']->field_run_date->start_date;
    $end_date = $variables['node']->field_run_date->end_date;
    
    // Check for right time format
    $start_format = 'qh_date';
//    $round = date('i', $start_date->getTimestamp());
//    if ($round != '00') {
//      $start_format = 'lc_time_minutes';
//    }    
    $st_time = \Drupal::service('date.formatter')->format($start_date->getTimestamp(), $start_format);

    // Check for right time format
    $end_format = 'qh_date';
//    $round = date('i', $end_date->getTimestamp());
//    if ($round != '00') {
//      $end_format = 'lc_time_minutes';
//    }  
    $en_time = \Drupal::service('date.formatter')->format($end_date->getTimestamp(), $end_format);
    
    // See if start and end are the same
    if ($st_time == $en_time) {
      $variables['at_time'] = $st_time.' '.t('Multiple times');;
    }
    else {
       $variables['at_time'] = $st_time.'-'.$en_time;
    }
    
    //$variables['at_date'] = \Drupal::service('date.formatter')->format($start_date->getTimestamp(), 'qh_date');
   // $variables['startdate'] = \Drupal::service('date.formatter')->format($start_date->getTimestamp(), 'qh_dm');
    //$variables['enddate'] = \Drupal::service('date.formatter')->format($end_date->getTimestamp(), 'qh_dm');
    //$variables['year'] = \Drupal::service('date.formatter')->format($end_date->getTimestamp(), 'qh_y');
  //  $variables['day'] = \Drupal::service('date.formatter')->format($start_date->getTimestamp(), 'qh_day');
//    if (isset($do_time)) {
//      $variables['do_time'] = $do_time == '' ? 'AT ' . $variables['at_time'] : 'DOORS ' . $do_time;
//    }
  }   
}

/**
 * Implements hook_form_alter()
 */
function spektrix_import_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Remove rollback option from migrate UI
  if ($form_id == 'migration_execute_form') {
	unset($form['operations']['operation']['#options']['rollback']);
  }
}

/**
 * hook_page_attachments_alter()
 */
function spektrix_import_page_attachments_alter(&$page){
  $page['#attached']['library'][] = 'core/drupal.ajax';
  $page['#attached']['library'][] = 'spektrix_import/spektrix_iframe_resize';
}

/**
 * Preprocess entity
 */
function spektrix_import_preprocess_eck_entity(&$vars) {  
  if (isset($vars['elements']['#extra_content']) && is_object($vars['elements']['#extra_content'])) {    
	if ($vars['elements']['#extra_content']->bundle() == 'donation' || $vars['elements']['#extra_content']->bundle() == 'spektrix_donation') {      
      $vars['spektrix_client'] = \Drupal::config('spektrix_import.settings')->get('spektrix_import_client');
	  $vars['fund_id'] = $vars['elements']['#extra_content']->field_fund->getString();
      $vars['custom_domain'] = \Drupal::config('spektrix_import.settings')->get('spektrix_import_domain');
	}
  }
}

/**
 * Add dynamic library definitions.
 *
 * Modules may implement this hook to add dynamic library definitions. Static
 * libraries, which do not depend on any runtime information, should be declared
 * in a modulename.libraries.yml file instead.
 *
 * @return array[]
 *   An array of library definitions to register, keyed by library ID. The
 *   library ID will be prefixed with the module name automatically.
 *
 * @see core.libraries.yml
 * @see hook_library_info_alter()
 */
function spektrix_import_library_info_build() {
  
  $libraries = [];
  $config = \Drupal::service('config.factory')->get('spektrix_import.settings');
  $domain = $config->get('spektrix_import_domain');
  $user = $config->get('spektrix_import_client');
  
  // Add a library whose information changes depending on certain conditions.
  $libraries['spektrix_iframe_resize'] = [
    'js'  => [
      'https://' .$domain .'/'. $user .'/website/scripts/integrate.js' => [
        'type'  =>  'external'
      ]
    ]
  ];
  
  return $libraries;
  
}