administerusersbyrole.settings:
  type: config_object
  label: 'Administer Users by Role settings'
  mapping:
    roles:
      type: sequence
      label: 'Roles'
      sequence:
        type: string
        label: 'Role'
