ignored_config_entities:
  - stage_file_proxy.settings
  - yv_tnew.settings
  - google_analytics.settings
  - system.performance
  - 'block.*'
  - spektrix_import.settings
_core:
  default_config_hash: claOMBKuXMxbMKaC3_4aLztnH3sMbzAyQo28b6PDh34
