module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  administerusersbyrole: 0
  anchor_link: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  block_content_permissions: 0
  block_region_permissions: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  devel_entity_updates: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  eck: 0
  editor: 0
  editor_advanced_link: 0
  embed: 0
  entity_browser: 0
  entity_embed: 0
  field: 0
  field_group: 0
  field_tools: 0
  field_ui: 0
  file: 0
  file_browser: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  imageapi_optimize: 0
  imageapi_optimize_resmushit: 0
  inline_entity_form: 0
  kint: 0
  link: 0
  linkit: 0
  m4032404: 0
  menu_block: 0
  menu_block_title: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  migrate: 0
  migrate_plus: 0
  migrate_tools: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  prepopulate: 0
  publishcontent: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  rename_admin_paths: 0
  roleassign: 0
  shortcut: 0
  smart_trim: 0
  soundcloudfield: 0
  spektrix_import: 0
  structure_sync: 0
  syd_tweaks: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  user: 0
  video_embed_field: 0
  view_unpublished: 0
  views_bulk_operations: 0
  views_ui: 0
  menu_admin_per_menu: 1
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  views: 10
  syd_profile: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  pippip: 0
profile: syd_profile
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
