country:
  default: GB
first_day: 1
timezone:
  default: Europe/London
  user:
    configurable: false
    warn: false
    default: 0
_core:
  default_config_hash: dwa-elCu4MQe3crZz6QWptmuIzgEj28qFLSIAWKIIzM
